### ISSUE TITLE
Rotate Blocks?

### ISSUE THREAD

**Issue by nardev** [alankrantas/pxt-MAX7219_8x8#3]
Hi, is there a way to rotate blocks? Some modules are already interconnected in a different way, is it possible to make that with this lib too?

![img_20190304_034944](https://user-images.githubusercontent.com/696054/53707820-de461d00-3e30-11e9-93f6-3ce764dfd3e9.jpg)

**Comment by alankrantas** [comment]
@nardev I'll see what can I do, but it may take some time. In my country we don't have these kind of linked modules.

MAX7219s are updated by columns (every column are represented by a byte number as the status of 8 LEDs), so I'll probably have to remap each 8 columns back to a 8x8 array, rotate the array then update them to modules.

**Comment by nardev** [comment]
😥😥😥 i need that for the kids, this Friday 😥😥😥

**Comment by alankrantas** [comment]
@nardev Yes, and I have tons of actual work to to, which pays for these free contributions. You have my sympathy, and all I ask from you is patience.

**Comment by nardev** [comment]
Don't get me wrong, I understand 100%

**Comment by nardev** [comment]
I just made a pull request, i would appreciate if you can merge it asap.

thnx

**Comment by alankrantas** [comment]
The _displayArray is in fact a long single-axis array representing each column (its binary sum) of the LED display, not 2-axis 8x8 matrixs. So there's no point to "rotate" that array anyway. There's about 4 or 5 places need to modify too, not just the part you added.

I'll try to work on this when I get off work (about 8-9 hours from now). But like I said, there are other priorities and I cannot sacrifice them right away simply for your need.

**Comment by nardev** [comment]
Anyway, than you so much. I needed this so i had to make quick fix. It works at least.

**Comment by alankrantas** [comment]
Rotate feature added. Not just one but all four printing functions.

**Comment by nardev** [comment]
Just tested the "rotate" feature. It mixes the blocks. Actually it mixes the start side of block. Do you need picture?

**Comment by alankrantas** [comment]
Yes, please give pictures or videos, maybe some detailed photos of your module, about how and which direction they wired together, and which direction should I rotate. (Probably I'll add the option to rotate either direction.) Not sure what “mix the block” means.

**Comment by nardev** [comment]
![IMG_20190309_060244](https://user-images.githubusercontent.com/696054/54066484-213d3180-4231-11e9-91d1-b7b0a4ef2a41.jpg)
![IMG_20190309_055611](https://user-images.githubusercontent.com/696054/54066485-213d3180-4231-11e9-9324-efcb7b276c81.jpg)
![IMG_20190309_055748](https://user-images.githubusercontent.com/696054/54066486-213d3180-4231-11e9-8757-a62e4c244271.jpg)
![IMG_20190309_055804](https://user-images.githubusercontent.com/696054/54066487-213d3180-4231-11e9-8028-bb7641f72085.jpg)

[VID_20190309_055634.zip](https://github.com/alankrantas/pxt-MAX7219_8x8/files/2948086/VID_20190309_055634.zip)

**Comment by alankrantas** [comment]
I guess your module is wired in the different order as I originally thought; it is ordered as

wire   0   1   2   3

or I should say

3   2   1   0   wire

and mine is

wire   3   2   1   0

Chained MAX7219s are updated by keep pushing data toward the end of the chain. I'll try inverting the pushing order to see if that works.

**Comment by alankrantas** [comment]
Alright, I made a little change to reverse the printing order. Tell me if that works, if the direction is right.

**Comment by alankrantas** [comment]
I've made some changes (I guess it was because the rotation direction was wrong), but since I do not have the appropriate hardwares I cannot verify it further. I'll close the issue and leave the rotation feature as experimental.

**Comment by nardev** [comment]
Ill test it today. Thnx

**Comment by nardev** [comment]
Sadly, not fixed.

Check the video: https://drive.google.com/open?id=1mvjENGQX4dFGuRCmIWUyxI20fy7d4OzT

**Comment by alankrantas** [comment]
Updated. Try again.

**Comment by nardev** [comment]
Again, doesn't work.

Maybe if you check this image to see how the blocks are connected:

![image](https://user-images.githubusercontent.com/696054/54471917-fa4aa680-47c0-11e9-9d08-c6ae2e3264ae.png)


Here is video for latest version you pushed: https://drive.google.com/open?id=1rU1M1-6y_8FoSWcU1DC_XQUqMre-Tl0P

**Comment by alankrantas** [comment]
It looks exactly the same as your previous video - which means you are still running on the older code.

If you downloaded it directly from MakeCode editor it will get the latest release version (in this case v0.0.2) instead the latest modified files.

I've re-publish the v0.0.2 release, and please do try again.

**Comment by nardev** [comment]
I really opened clean environment and added the new library and blocks. I'll try one more time bit later. Please don't close the issue.

**Comment by nardev** [comment]
Man, it definitely doesn't work again.

Tried 100% clean environment.

**Comment by alankrantas** [comment]
It never worked for me, because despite your photo I don't know how your hardware are actually wired inside; it could be very different from mine, as far as I know.

So here's how we proceed next:

1. I need a video of your module running the "normal" scrolling code, scrolling slowly please. I need to see the moving direction of the text (which I definitely cannot tell in your blurry photos).

2. Print number 0 on matrix index 0, number 1 on matrix index 1, and so on. Show me the result photo.

**Comment by alankrantas** [comment]
By a way of solution I made a new block, which allows you to choose which direction to rotate (include 180 degrees), and if you want to reverse the printing order. It works on my device anyway.

![1](https://user-images.githubusercontent.com/44191076/54478164-47268f80-484a-11e9-98de-76c1406e43e3.jpg)

Go give it a try.

**Comment by nardev** [comment]
"counter-clockwise" is the only that works.

maybe you could try to add direction "left->right" too

**Comment by alankrantas** [comment]
You are welcome.

This issue is officially closed.
