### ISSUE TITLE
Make "1" the same width as the other digits

### ISSUE THREAD

**Issue by objorke** [alankrantas/pxt-MAX7219_8x8#7]
Fixed-width will make it easier to show for example running time without digits moving back and forth...
``
           [0b01000010,
            0b01111111,
            0b01000000,
            0b00000000,
            0b00000000],
``

**Comment by alankrantas** [comment]
I see you've already did your own modification. So I guess you can import your own extension instead. The font I've used is not monospaced, so the "problem" still exists in many other characters too. 

[MicroPython](https://micropython.org/) has a built-in monospaced 8x8 font, which works on MAX7219 display.
